# Generated by Django 2.2.5 on 2019-12-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stes_test', '0003_question_answers_attempted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam_questions',
        ),
    ]
